PACKAGE_NAME = "cn.imsummer.summer"
ADB_KEYBOARD_IME = "com.android.adbkeyboard/.AdbIME"


class Ids:
    TITLE = f"{PACKAGE_NAME}:id/title"
    TOOLBAR_TITLE = f"{PACKAGE_NAME}:id/toolbar_title"

    MAIN_TAB_LABEL = f"{PACKAGE_NAME}:id/main_tab_laber_tv"

    MESSAGE_LIST = f"{PACKAGE_NAME}:id/main_msg_notification_rv"
    MESSAGE_NICKNAME = f"{PACKAGE_NAME}:id/msg_item_nickname_tv"
    MESSAGE_PREVIEW = f"{PACKAGE_NAME}:id/msg_item_msg_tv"
    MESSAGE_TIME = f"{PACKAGE_NAME}:id/msg_item_time_tv"

    CHAT_INPUT = f"{PACKAGE_NAME}:id/et_sendmessage"
    CHAT_SEND = f"{PACKAGE_NAME}:id/btn_send"
    CHAT_MORE = f"{PACKAGE_NAME}:id/btn_more"
    CHAT_CONTENT = f"{PACKAGE_NAME}:id/tv_chatcontent"

    NEARBY_LIST = f"{PACKAGE_NAME}:id/child_nearby_rv"
    FRIEND_LIST = f"{PACKAGE_NAME}:id/friend_friend_rv"
    USER_NICKNAME = f"{PACKAGE_NAME}:id/nearby_user_item_nickname"
    USER_SCHOOL = f"{PACKAGE_NAME}:id/nearby_user_item_school"
    USER_AGE = f"{PACKAGE_NAME}:id/nearby_user_item_age"
    USER_DISTANCE = f"{PACKAGE_NAME}:id/nearby_user_item_distance"
    USER_BIO = f"{PACKAGE_NAME}:id/nearby_user_item_bio"

    PAPER_LIST = f"{PACKAGE_NAME}:id/other_paper_rv"
    PAPER_TITLE = f"{PACKAGE_NAME}:id/paper_title_tv"
    PAPER_SEQUENCE = f"{PACKAGE_NAME}:id/paper_seq_type_tv"
    PAPER_ESSAY = f"{PACKAGE_NAME}:id/paper_essay_et"
    PAPER_CHOICE_GROUP = f"{PACKAGE_NAME}:id/paper_choice_rg"
    PAPER_PUBLIC_SWITCH = f"{PACKAGE_NAME}:id/public_sc"
    PAPER_CONFIRM = f"{PACKAGE_NAME}:id/other_paper_confirm_tv"

    FILTER_BUTTON = f"{PACKAGE_NAME}:id/nearby_filter_iv"
    FILTER_CONFIRM = f"{PACKAGE_NAME}:id/toolbar_menu_title"
    FILTER_GENDER_ALL = f"{PACKAGE_NAME}:id/nearby_filter_gender_all"
    FILTER_GENDER_MALE = f"{PACKAGE_NAME}:id/nearby_filter_gender_boy"
    FILTER_GENDER_FEMALE = f"{PACKAGE_NAME}:id/nearby_filter_gender_girl"
    FILTER_RELATIONSHIP_ALL = f"{PACKAGE_NAME}:id/nearby_filter_relationship_status_all"
    FILTER_RELATIONSHIP_SINGLE = f"{PACKAGE_NAME}:id/nearby_filter_relationship_status_single"
    FILTER_ACTIVE_ALL = f"{PACKAGE_NAME}:id/nearby_filter_active_status_all"
    FILTER_ACTIVE_TODAY = f"{PACKAGE_NAME}:id/nearby_filter_active_status_today"
    FILTER_SEXUAL_ALL = f"{PACKAGE_NAME}:id/sexual_all_rb"
    FILTER_SEXUAL_OPPOSITE = f"{PACKAGE_NAME}:id/sexual_diff_rb"
    FILTER_SEXUAL_SAME = f"{PACKAGE_NAME}:id/sexual_same_rb"
    FILTER_PHOTOS_ALL = f"{PACKAGE_NAME}:id/nearby_filter_is_have_photos_all"
    FILTER_PHOTOS_HAVE = f"{PACKAGE_NAME}:id/nearby_filter_have_photos"
    FILTER_DEPARTMENT = f"{PACKAGE_NAME}:id/department_et"

    SCHOOL_LIST = f"{PACKAGE_NAME}:id/school_rv"
    SCHOOL_SEARCH = f"{PACKAGE_NAME}:id/tv_search"
    SCHOOL_NAME = f"{PACKAGE_NAME}:id/name"
    SCHOOL_MALE = f"{PACKAGE_NAME}:id/male"
    SCHOOL_FEMALE = f"{PACKAGE_NAME}:id/female"
    SCHOOL_DISTANCE = f"{PACKAGE_NAME}:id/distance"
